name: ArchCoreSystem
author: GamerXzavier
main: ARCHCore\Main
api: [2.0.0]
version: 0.1#Beta
commands:
 help:
  usage: /help or /?
  description: Help Command
 news:
  description: See Newss!!
 stats:
  permission: rpg.stats
  default: true

  permissions:
    N.F.D:
      default: true
    rpg.stats:
       default: true
       description: "Shows Your stats"

